vich_uploader:
    db_driver: orm

    mappings:
        profiles:
            uri_prefix: /assets/profilees
            upload_destination: '%kernel.project_dir%/public/assets/profiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
