vich_uploader:
    db_driver: orm

    mappings:
        profiles:
            uri_prefix: /assets/profiles
            upload_destination: '%kernel.project_dir%/public/assets/profiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        covers:
            uri_prefix: /assets/covers
            upload_destination: '%kernel.project_dir%/public/assets/covers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer